spring:
  cloud:
    gateway:
      discovery.locator.enabled: true
      routes:
        - id: shopping_cart_service_route
          uri: lb://shopping-cart
          predicates:
            - Path=/shopping-cart/**
          filters:
            - PrefixPath=/api/v1
#            - CircuitBreaker=myCircuitBreaker
        - id: shopping-store_service_route
          uri: lb://shopping-store
          predicates:
            - Path=/shopping-store/**
            - Path=/shopping-store/{id}
          filters:
            - PrefixPath=/api/v1
#            - CircuitBreaker=myCircuitBreaker

server:
  port: 8080

#resilience4j.circuitbreaker:
#  instances:
#    myCircuitBreaker:
#      slidingWindowSize: 10
#      failureRateThreshold: 50
#      waitDurationInOpenState: 10000 # 10 секунд в миллисекундах
#      permittedNumberOfCallsInHalfOpenState: 3
#      slidingWindowType: COUNT_BASED
#      minimumNumberOfCalls: 5
#      automaticTransitionFromOpenToHalfOpenEnabled: true